path:
    upload_folder: '/home/moss/Desktop/Internships Stuff/NOKIA/Map-Clustering/'

api:
    google_maps_js: AIzaSyCPsR-n1YeVpLQeOa4Yjp5-mJz_DuOEn78

allowed_extension: ['xlsx', 'kml']

github:
    handle: 'VarunBhandia'
    password: 'rj14cn2847'
    repo: 'test'
    branch: 'master'